//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projek.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHeader
    {
        public int TransactionId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
    }
}
